name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: "main"
          healthcheck: https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/api/v1/health
          rollbackonhealthcheckfailed: true
          delay: 15
          # A buildpack to use poetry on Heroku.
          buildpack: https://github.com/moneymeets/python-poetry-buildpack.git
        env:
          HD_DEBUG: False
          # Prevent poetry buildpack from creating a `runtime.txt` file.
          HD_DISABLE_POETRY_CREATE_RUNTIME_FILE: 1
